[book]
authors = ["Drew Thomas"]
language = "en"
multilingual = false
src = "src"
title = "drewthomas.dev"

[output.html]
git-repository-url = "https://github.com/CDThomas/drewthomas-dev"
no-section-label = true

[output.html.print]
enable = false

[output.linkcheck]
